spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
jpa:
  show-sql: true

server:
  context-path: /sell



#https://gitee.com/search?search=weixin-sell&group_id=&project_id=&type=

#logging.pattern.console=%d - %msg%n